# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        metric learning: 3
        texture: 3
        shape bias: 2
        imagenet: 1
        fractal: 2
        ensemble: 3
        transformer: 1
        factual inconsistency: 3
        factual consistency: 3
        factual: 1
        

# 通知の閾値
score_threshold: 0
